export enum TYPE_NOTIFICATION {
  TRIP_REQUEST = 'TRIP_REQUEST',
  VEHICLE_REQUEST = 'VEHICLE_REQUEST',
  DRIVER_REGISTER = 'DRIVER_REGISTER',
  USER_BUYPACKAGE = 'USER_BUYPACKAGE',
  USER_SEND_FEEDBACK = 'USER_SEND_FEEDBACK',
}
